# Site settings
author: DAZUN XING
title: Online Software Engineering
header-img: img/home-bg.png
email: dazun.xing@gmail.com
copyright_name: DAZUN XING
description: > # this means to ignore newlines until "baseurl:"
  Cohort
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  xdzorc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
